version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: kirppis-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=kirppis

  # Backend service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: kirppis-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongo:27017/kirppis
      - UPLOAD_DIR=/app/uploads
    volumes:
      - uploads_data:/app/uploads

  # Frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: kirppis-client
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:5000/api/v1

volumes:
  mongo_data:
  uploads_data: 