version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - HOST=0.0.0.0
      - PORT=${PORT:-3000}
      - MONGO_URI=mongodb://mongodb:27017/${MONGO_DB_NAME:-kirppis}
    volumes:
      - ./client:/app/client
      - ./server:/app/server
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/database/init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"

volumes:
  mongodb_data: 